name: Midnight run

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          touch .env
          echo GARMIN_EMAIL=${{ secrets.GARMIN_EMAIL }} >> .env
          echo GARMIN_PASSWORD=${{ secrets.GARMIN_PASSWORD }} >> .env
          cat .env

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt # TODO clean up requirements.txt

      - name: Generate Wainright map
        run: python generate_wainright.py

      - name: Update last updated timestamp
        run: date +'%Y-%m-%d %H:%M:%S' > docs/last_updated.txt

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/* GPX_files/*.gpx
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate HTML $(date +'%Y-%m-%d %H:%M:%S')" && git push)
